### ISSUE TITLE
Doesn't respect the deck field

### ISSUE THREAD

**Issue by HappyRay** [ThoreBor/CC-CEDICT-for-Anki#1]
Thanks for creating this tool!

I tried it today. It worked for me.
The only problem I have seen so far is that it doesn't allow me to change the desk after the initial test.
I've tried deleting the addon and reinstalling it/ changing the config.
After I delete the test desk, it creates new cards in a deck that I don't seem to have control anymore. For example, it currently saves only to the default desk.

My version:
v1.2 (14.02.2020):
Version 2.1.33 (3f403040) on Mac
Python 3.8.0 Qt 5.14.2 PyQt 5.14.2

**Comment by ThoreBor** [comment]
What exactly do you mean with  
> it doesn't allow me to change the deck

Are you not able to choose a deck from the dropdown menu, or are new cards not added to the deck you chose?

**Comment by HappyRay** [comment]
I can choose a desk from the dropdown menu.
However new cards are not added to the desk I chose.
Thanks
