### ISSUE TITLE
KaiTi font family not found

### ISSUE THREAD

**Issue by HappyRay** [ThoreBor/CC-CEDICT-for-Anki#13]
I saw this message today while debugging an issue.

I am on Mac.

(python-3.8.5)[~/oss/cc-cedict-for-anki (debug-note-type-issue *)]$ /Applications/Anki.app/Contents/MacOS/Anki
mpv too old for key rebinding
Qt WebEngine resources not found at . Trying parent directory...
Qt WebEngine resources not found at /Applications/Anki.app/Contents/MacOS/PyQt5/Qt. Trying application directory...
Installed Qt WebEngine locales directory not found at location /qtwebengine_locales. Trying application directory...
qt.qpa.fonts: Populating font family aliases took 134 ms. Replace uses of missing font family "KaiTi" with one that exists to avoid this cost.

**Comment by ThoreBor** [comment]
Okay, thanks for letting me know. Works for me, but I changed to font back to SimHei for now.

**Comment by HappyRay** [comment]
Thanks. 

It seems that the old font has a similar issue.

"(python-3.8.5)[~/oss/cc-cedict-for-anki (re-organize-folders *+)]$ /Applications/Anki.app/Contents/MacOS/Anki
mpv too old for key rebinding
Qt WebEngine resources not found at . Trying parent directory...
Qt WebEngine resources not found at /Applications/Anki.app/Contents/MacOS/PyQt5/Qt. Trying application directory...
Installed Qt WebEngine locales directory not found at location /qtwebengine_locales. Trying application directory...
qt.qpa.fonts: Populating font family aliases took 122 ms. Replace uses of missing font family "SimHei" with one that exists to avoid this cost.
"

It's not a big deal. Mine continues to work despite this warning.

**Comment by ThoreBor** [comment]
Okay, I just realized that SimHei is a Microsoft font and the default Chinese font on windows. That's probably why it doesn't work on mac.  What's the default on mac?

**Comment by HappyRay** [comment]
According to https://en.wikipedia.org/wiki/List_of_CJK_fonts, there doesn't seem to be a Chinese font that are on mac and windows by default.

It's ok. The problem doesn't seem to affect me much.
