### ISSUE TITLE
Bug: "1 new card was added"

### ISSUE THREAD

**Issue by sykul** [ThoreBor/CC-CEDICT-for-Anki#20]
How to recreate: Add a new word using the pop-up dialogue box.
Expected behaviour: A message should tell you that a *note* has been added. Or, if the note type you've selected has more than one card type associated with it, the message could tell you how many cards were created.
Actual behaviour: A message tells you that "1 new card was added", which is not true if the note type has more than 1 card type.

**Comment by ThoreBor** [comment]
Yes, that's a mistake. I'll fix it. Thanks!

**Comment by ThoreBor** [comment]
Just realized that I already fixed that, but didn't release it yet.
