### ISSUE TITLE
v1.3-beta: Error when attempting to install

### ISSUE THREAD

**Issue by sykul** [ThoreBor/CC-CEDICT-for-Anki#22]
Anki Version ⁨2.1.46 (94913ec2)⁩ 

When installing from file either by opening the .ankiaddon file directly in Anki or using the Addon Manager within Anki, I get the following error message "Error installing ⁨CC-CEDICT-for-Anki-v1.3-beta.ankiaddon⁩: ⁨Invalid add-on manifest.⁩"

**Comment by ThoreBor** [comment]
Sorry, my bad. I forgot to add a file. It should work now

**Comment by sykul** [comment]
Able to install now and looks great. I'll give it a try now and let you know if there any more issues.

Really appreciate your work and the speed of your responses. Thanks a lot :1st_place_medal:
