### ISSUE TITLE
Some vocab entries don't map correctly to the note's fields

### ISSUE THREAD

**Issue by adamclarence** [ThoreBor/CC-CEDICT-for-Anki#23]
This first image shows an example of a word for which I tried to create a note but the mapping failed (电影). Note the set-up of the fields: the note should have the English meaning, the pinyin, and then the characters. This ordering is certainly correct for my notetype, and it works for most (probably ~95%) additions through CC-CEDICT.

![image](https://user-images.githubusercontent.com/19248619/130222716-b173cd09-2638-4e4e-9e70-8835da78a73a.png)

However, the created note is all wrong:

![image](https://user-images.githubusercontent.com/19248619/130223462-d56d0de0-bada-41ce-9514-6e724e78c6d0.png)

- Whether a note is successfully created or not from each vocab item seems fixed: for the ones that failed, trying again always leads to failure, and for the ones that succeed, trying again always leads to success.
- I think that the failure is *probably* to do with having multiple classifiers listed together in the English definition. The failures that I examined all had this in common (and were incorrectly split across the fields between the different classifiers listed), and I did not spot a note that was successfully created and had multiple classifiers listed together.

**Comment by ThoreBor** [comment]
Thanks for letting me know. I'm about to release an update, so could you check if you still have the problem if you use the pre-release of v1.3? You can download it [here](https://github.com/ThoreBor/CC-CEDICT-for-Anki/releases) (just open the .ankiaddon file).

**Comment by adamclarence** [comment]
Ah, excellent — the issue is gone in v1.3. Thank you :)
