### ISSUE TITLE
When will the new 1.3 version be released?

### ISSUE THREAD

**Issue by HappyRay** [ThoreBor/CC-CEDICT-for-Anki#24]
It's great to see a new pre-release version 1.3 Beta. I am looking forward to using it!

When do you plan to release it to the addon page https://ankiweb.net/shared/info/418828045?

In the meantime, is there a way to try it?

**Comment by ThoreBor** [comment]
I think I could release it now unless @sykul has any complaints. You can try it by downloading the .ankiaddon file from [here](https://github.com/ThoreBor/CC-CEDICT-for-Anki/releases).

**Comment by sykul** [comment]
I've been using it for a while and no huge complaints. I'd say it's ready for release. I only have a minor UI issue. I'll open up another issue for it.

**Comment by ThoreBor** [comment]
It's now on ankiweb
