### ISSUE TITLE
Make it possible for the window to be resized to a smaller size

### ISSUE THREAD

**Issue by sykul** [ThoreBor/CC-CEDICT-for-Anki#25]
At the moment the minimum window size is over half the width of my screen. It would be good to have the window in the corner of the screen while your Chinese content takes up most of the rest of the screen.
This might cover up some of the buttons and menus, but once you've selected the card type and deck, all you really need is the search functionality, a preview, and the 'Add Card(s)' button.

**Comment by ThoreBor** [comment]
I think being able to quickly change decks is good, so I don't know if I want to move those things to a different window.
Would this work for now? It's not super pretty but might be enough for you:

https://user-images.githubusercontent.com/40232329/131881919-b14f85b7-f2d2-41be-b9fc-6056552a1944.mp4

**Comment by sykul** [comment]
In my use case, I only have one Chinese deck and note type, but you're probably right that many people would need the deck and note options readily available. 
I would have to try it out to be sure but that preview looks pretty good.

**Comment by ThoreBor** [comment]
Alright, I'll release it on ankiweb then. I'll keep this issue open for now though
