### ISSUE TITLE
Feature request: recognize multiple words separated by tab, colons, linefeeds (new line marks)

### ISSUE THREAD

**Issue by camerooncameroon** [ThoreBor/CC-CEDICT-for-Anki#28]
Hello, thanks for the great tool for Chinese learner Anki user!
Recent update added the option to insert many words comma separated.
Pls also add the ability to input arrays of word separated by other common marks like linefeeds (it's classic word list exported by huge amount of different programs/plugins) or (semi)colons, tabs etc. 
If it's possible then make it user-defineable which symbol is used to separate words.

**Comment by ThoreBor** [comment]
Sure, I'll add it in the next update, but I don't know when this will be. If you want to add it yourself on your end, you can just add your separators in [this line](https://github.com/ThoreBor/CC-CEDICT-for-Anki/blob/819cc6d8f582921c037d9c884d3daa49db382528/cedict/main.py#L31)  in the meantime.

**Comment by camerooncameroon** [comment]
@ThoreBor 
Thanks, great!
Tried \n for new line, it didn't work. How to add new line feed to the separators?
Tabs worked when I just added it to the string (literally just hit 'tab' button on my keyboard).
Space also worked (the self space, after hitting the keyboards 'space bar').

I only didn't find how to add the new line feed for word lists like:
中国
美国
德国
俄国
法国
英国
日本
...
Here (and in text editors) it looks like multiline text (which it actually is), but in the addon search field it's shown as a single line with some hidden separators which is new line feeds:

![image](https://user-images.githubusercontent.com/78047188/143700381-4c4fef53-e8a6-483a-8e72-de8a3c237d12.png)

But when I copy this new line feed sign and paste it to this string:
`31	return [w.strip() for w in re.split(r'[，,#%&$/ 	]', s)]`
the line is broken into two lines:
`31	return [w.strip() for w in re.split(r'[，,#%&$/ 	`
` ]', s)]`
and addon shows error.

What symbol should be added to this string in the `main.py` file for the addon to render new line feeds signs as input search words separators?

**Comment by ThoreBor** [comment]
This works for me:
`return [w.strip() for w in re.split(r'[\n，,#%&$/ ]', s, re.M)]`
Turns out that [in a regular expression, you need to specify that you're in multiline mode](https://stackoverflow.com/a/14689821/13237966)
Hope this helps.

**Comment by camerooncameroon** [comment]
Works great! Thanks! now it's possible to mass-add new cards from lists made in many other programs

**Comment by ThoreBor** [comment]
Great! I'll add this to the next version then, as it might be useful for other people as well.

**Comment by camerooncameroon** [comment]
I only added tab to your line for tab-fans ))
This resulted in:
`	return [w.strip() for w in re.split(r'[\n，,#%&$/ 	]', s, re.M)]
`

**Comment by camerooncameroon** [comment]
@ThoreBor 

Actually the search method you implemented is so awesome I wish Anki had it as built-in option in Anki's own search dialog.

Of course the already present in Anki search regexp is powerful and can do almost everything - but your natural and intuitive search, where you can just copy-paste and instantly have your desired words filtered (without preformatting of the query) - is much more simple, even for people who aren't even aware of regexps )).

can your implementation be also applied to the Anki's own search dialog? as a built-in option or an addon?
