### ISSUE TITLE
definition field contains commas but cards are created without them (only a space separating definitions), they are hard to read. Also, can the cursor be positioned on the search bar when opening the add-on window?

### ISSUE THREAD

**Issue by Edgar-Galan** [ThoreBor/CC-CEDICT-for-Anki#29]
My cards are being generated the the definition field separated by single spaces, which make them confusing and hard to read for words containing multiple definitions (most). I am not sure why since definitions within the add-on window are comma-separated, still cards appear with single spaces only. 

Another thing, which I hope is simple to implement, would be to position the cursor on the search bar when opening the add-on, since that is pretty much the only thing people want to use when opening it. Right now it is necessary to use the mouse and click there every time (tab does not get there).

Sorry, for combining multiple suggestions in one post. Finally, I would like to know if it is possible to select the fields used for duplicate checking? or it is up to Anki only? My problem is that I have cards added from other apps or manually. This add-on will readily add duplicates even when simplified and traditional fields are the same, so long as definition fields is different. For example the dictionary on my phone will add cards with definitions that are separated by a symbol or a semicolon (from CC-CEDICT too), and this add-on add them separated by spaces and counts them as different cards. If possible I would select either simplified or traditional fields for duplicate checking only, so even if definitions differ the add-on can warn me these are duplicates.

Cheers.

**Comment by Edgar-Galan** [comment]
Sorry, I just realized the add-on does not create cards with definitions separated by single spaces. It actually creates them separated by line breaks as follows: 

![image](https://user-images.githubusercontent.com/73632883/158328493-2068b638-bf36-4edd-b232-d22074870e75.png)

Then Anki displays them as continuous text as below:

![image](https://user-images.githubusercontent.com/73632883/158328528-08ab1abb-2811-4494-bd2e-6bcd7e087dc7.png)

So, for this issue, I will find a solution to prevent Anki from displaying this as continuous text, rather than separate lines.

**Comment by ThoreBor** [comment]
Hi!
I just fixed the first two things. About the duplicates, I'm not sure how well it's gonna work. I changed it to check all fields now, but they really have to be identical to be considered a duplicate. I'll release the update soon.
