### ISSUE TITLE
The search input box's initial size is too small

### ISSUE THREAD

**Issue by HappyRay** [ThoreBor/CC-CEDICT-for-Anki#9]
Please see the screenshot
<img width="1095" alt="anki Chinese addon small search input box" src="https://user-images.githubusercontent.com/6646529/93655934-83a4ef80-f9db-11ea-83de-5b787c3c3b3c.png">

**Comment by ThoreBor** [comment]
It doesn't look like that on windows (at least for me). I uploaded a quick fix that should probably resolve this for you. As I said, I'm planning to make some adjustments, mainly that you can change the window size (use fullscreen) and everything looks nice and proportionate. 
I also might change QListWidget to QTableWidget for the results and the dictionary entry on the top right could also look prettier. 
If this doesn't work, just use the .ui file from a couple of commits back.

**Comment by HappyRay** [comment]
Thanks. 
Yes, I am on Mac. 
Your latest change helped a bit. But the size is still too small to be usable.
I reverted to your earlier version of the ui file for now. 
I am not familiar enough with QT yet to make the fix myself.

**Comment by HappyRay** [comment]
Thanks
